WIDTH = 800               # Largura da janela em pixels.
HEIGHT = 600              # Altura da janela em pixels.
FPS = 50                  # Quadros por segundo (estabilidade visual).
PLAYER_SIZE = (32,32)     # Tamanho padrão para o colisor do jogador.
PLAYER_SPEED = 200        # Velocidade base (pixels por segundo).
TITLE = "Meu Jogo"        # Nome que aparece na barra da janela.
BG_COLOR = (120, 130, 100)# Cor de fundo em formato RGB.
COIN_COUNT = 5            # Quantidade de moedas geradas por vez.
FONT_SIZE = 25
COIN_SPAWN_INTERVAL = 10.0 # Intervalo em segundos para gerar novas moedas.